use super::addrmode::AddrMode::{self, *};
use super::instruction::*;

pub struct OpCode<'a> {
    pub code: u8,
    pub instruction: &'a Instruction<'a>,
    pub addrmode: AddrMode,
    pub size: u8,
    pub cycles: u8,
}

impl<'a> OpCode<'a> {
    pub fn matches(&self, instruction: &Instruction, addrmode: AddrMode) -> bool {
        self.instruction == instruction && self.addrmode == addrmode
    }

    const fn new(code: u8, instruction: &'a Instruction, addrmode: AddrMode, cycles: u8) -> OpCode<'a> {
        OpCode {
            code,
            size: addrmode.operand_size() + 1,
            addrmode,
            instruction,
            cycles,
        }
    }
}

pub fn find_opcode<'a, 'b>(instruction: &'a Instruction, addrmode: AddrMode) -> Option<&'b OpCode<'b>> {
    OPCODES.iter().find(|oc| oc.matches(instruction, addrmode))
}

pub static OPCODES: [OpCode; 256] = [
    OpCode::new(0x00, &BRK, Implied, 7),
    OpCode::new(0x01, &ORA, IndexedIndirectX, 6),
    OpCode::new(0x02, &KIL, Implied, 0),
    OpCode::new(0x03, &KIL, Implied, 0),
    OpCode::new(0x04, &KIL, Implied, 0),
    OpCode::new(0x05, &ORA, ZeroPage, 3),
    OpCode::new(0x06, &ASL, ZeroPage, 5),
    OpCode::new(0x07, &KIL, Implied, 0),
    OpCode::new(0x08, &PHP, Implied, 3),
    OpCode::new(0x09, &ORA, Immediate, 2),
    OpCode::new(0x0a, &ASL, Implied, 2),
    OpCode::new(0x0b, &KIL, Implied, 0),
    OpCode::new(0x0c, &KIL, Implied, 0),
    OpCode::new(0x0d, &ORA, Absolute, 4),
    OpCode::new(0x0e, &ASL, Absolute, 6),
    OpCode::new(0x0f, &KIL, Implied, 0),
    OpCode::new(0x10, &BPL, Branch, 2),
    OpCode::new(0x11, &ORA, IndirectIndexedY, 5),
    OpCode::new(0x12, &KIL, Implied, 0),
    OpCode::new(0x13, &KIL, Implied, 0),
    OpCode::new(0x14, &KIL, Implied, 0),
    OpCode::new(0x15, &ORA, ZeroPageX, 4),
    OpCode::new(0x16, &ASL, ZeroPageX, 6),
    OpCode::new(0x17, &KIL, Implied, 0),
    OpCode::new(0x18, &CLC, Implied, 2),
    OpCode::new(0x19, &ORA, AbsoluteY, 4),
    OpCode::new(0x1a, &KIL, Implied, 0),
    OpCode::new(0x1b, &KIL, Implied, 0),
    OpCode::new(0x1c, &KIL, Implied, 0),
    OpCode::new(0x1d, &ORA, AbsoluteX, 4),
    OpCode::new(0x1e, &ASL, AbsoluteX, 7),
    OpCode::new(0x1f, &KIL, Implied, 0),
    OpCode::new(0x20, &JSR, Absolute, 6),
    OpCode::new(0x21, &AND, IndexedIndirectX, 6),
    OpCode::new(0x22, &KIL, Implied, 0),
    OpCode::new(0x23, &KIL, Implied, 0),
    OpCode::new(0x24, &BIT, ZeroPage, 3),
    OpCode::new(0x25, &AND, ZeroPage, 3),
    OpCode::new(0x26, &ROL, ZeroPage, 5),
    OpCode::new(0x27, &KIL, Implied, 0),
    OpCode::new(0x28, &PLP, Implied, 4),
    OpCode::new(0x29, &AND, Immediate, 2),
    OpCode::new(0x2a, &ROL, Implied, 2),
    OpCode::new(0x2b, &KIL, Implied, 0),
    OpCode::new(0x2c, &BIT, Absolute, 4),
    OpCode::new(0x2d, &AND, Absolute, 4),
    OpCode::new(0x2e, &ROL, Absolute, 6),
    OpCode::new(0x2f, &KIL, Implied, 0),
    OpCode::new(0x30, &BMI, Branch, 2),
    OpCode::new(0x31, &AND, IndirectIndexedY, 5),
    OpCode::new(0x32, &KIL, Implied, 0),
    OpCode::new(0x33, &KIL, Implied, 0),
    OpCode::new(0x34, &KIL, Implied, 0),
    OpCode::new(0x35, &AND, ZeroPageX, 4),
    OpCode::new(0x36, &ROL, ZeroPageX, 6),
    OpCode::new(0x37, &KIL, Implied, 0),
    OpCode::new(0x38, &SEC, Implied, 2),
    OpCode::new(0x39, &AND, AbsoluteY, 4),
    OpCode::new(0x3a, &KIL, Implied, 0),
    OpCode::new(0x3b, &KIL, Implied, 0),
    OpCode::new(0x3c, &KIL, Implied, 0),
    OpCode::new(0x3d, &AND, AbsoluteX, 4),
    OpCode::new(0x3e, &ROL, AbsoluteX, 7),
    OpCode::new(0x3f, &KIL, Implied, 0),
    OpCode::new(0x40, &RTI, Implied, 6),
    OpCode::new(0x41, &EOR, IndexedIndirectX, 6),
    OpCode::new(0x42, &KIL, Implied, 0),
    OpCode::new(0x43, &KIL, Implied, 0),
    OpCode::new(0x44, &KIL, Implied, 0),
    OpCode::new(0x45, &EOR, ZeroPage, 3),
    OpCode::new(0x46, &LSR, ZeroPage, 5),
    OpCode::new(0x47, &KIL, Implied, 0),
    OpCode::new(0x48, &PHA, Implied, 3),
    OpCode::new(0x49, &EOR, Immediate, 2),
    OpCode::new(0x4a, &LSR, Implied, 2),
    OpCode::new(0x4b, &KIL, Implied, 0),
    OpCode::new(0x4c, &JMP, Absolute, 3),
    OpCode::new(0x4d, &EOR, Absolute, 4),
    OpCode::new(0x4e, &LSR, Absolute, 6),
    OpCode::new(0x4f, &KIL, Implied, 0),
    OpCode::new(0x50, &BVC, Branch, 2),
    OpCode::new(0x51, &EOR, IndirectIndexedY, 5),
    OpCode::new(0x52, &KIL, Implied, 0),
    OpCode::new(0x53, &KIL, Implied, 0),
    OpCode::new(0x54, &KIL, Implied, 0),
    OpCode::new(0x55, &EOR, ZeroPageX, 4),
    OpCode::new(0x56, &LSR, ZeroPageX, 6),
    OpCode::new(0x57, &KIL, Implied, 0),
    OpCode::new(0x58, &CLI, Implied, 2),
    OpCode::new(0x59, &EOR, AbsoluteY, 4),
    OpCode::new(0x5a, &KIL, Implied, 0),
    OpCode::new(0x5b, &KIL, Implied, 0),
    OpCode::new(0x5c, &KIL, Implied, 0),
    OpCode::new(0x5d, &EOR, AbsoluteX, 4),
    OpCode::new(0x5e, &LSR, AbsoluteX, 7),
    OpCode::new(0x5f, &KIL, Implied, 0),
    OpCode::new(0x60, &RTS, Implied, 6),
    OpCode::new(0x61, &ADC, IndexedIndirectX, 6),
    OpCode::new(0x62, &KIL, Implied, 0),
    OpCode::new(0x63, &KIL, Implied, 0),
    OpCode::new(0x64, &KIL, Implied, 0),
    OpCode::new(0x65, &ADC, ZeroPage, 3),
    OpCode::new(0x66, &ROR, ZeroPage, 5),
    OpCode::new(0x67, &KIL, Implied, 0),
    OpCode::new(0x68, &PLA, Implied, 4),
    OpCode::new(0x69, &ADC, Immediate, 2),
    OpCode::new(0x6a, &ROR, Implied, 2),
    OpCode::new(0x6b, &KIL, Implied, 0),
    OpCode::new(0x6c, &JMP, Indirect, 5),
    OpCode::new(0x6d, &ADC, Absolute, 4),
    OpCode::new(0x6e, &ROR, Absolute, 6),
    OpCode::new(0x6f, &KIL, Implied, 0),
    OpCode::new(0x70, &BVS, Branch, 2),
    OpCode::new(0x71, &ADC, IndirectIndexedY, 5),
    OpCode::new(0x72, &KIL, Implied, 0),
    OpCode::new(0x73, &KIL, Implied, 0),
    OpCode::new(0x74, &KIL, Implied, 0),
    OpCode::new(0x75, &ADC, ZeroPageX, 4),
    OpCode::new(0x76, &ROR, ZeroPageX, 6),
    OpCode::new(0x77, &KIL, Implied, 0),
    OpCode::new(0x78, &SEI, Implied, 2),
    OpCode::new(0x79, &ADC, AbsoluteY, 4),
    OpCode::new(0x7a, &KIL, Implied, 0),
    OpCode::new(0x7b, &KIL, Implied, 0),
    OpCode::new(0x7c, &KIL, Implied, 0),
    OpCode::new(0x7d, &ADC, AbsoluteX, 4),
    OpCode::new(0x7e, &ROR, AbsoluteX, 7),
    OpCode::new(0x7f, &KIL, Implied, 0),
    OpCode::new(0x80, &KIL, Implied, 0),
    OpCode::new(0x81, &STA, IndexedIndirectX, 6),
    OpCode::new(0x82, &KIL, Implied, 0),
    OpCode::new(0x83, &KIL, Implied, 0),
    OpCode::new(0x84, &STY, ZeroPage, 3),
    OpCode::new(0x85, &STA, ZeroPage, 3),
    OpCode::new(0x86, &STX, ZeroPage, 3),
    OpCode::new(0x87, &KIL, Implied, 0),
    OpCode::new(0x88, &DEY, Implied, 2),
    OpCode::new(0x89, &KIL, Implied, 0),
    OpCode::new(0x8a, &TXA, Implied, 2),
    OpCode::new(0x8b, &KIL, Implied, 0),
    OpCode::new(0x8c, &STY, Absolute, 4),
    OpCode::new(0x8d, &STA, Absolute, 4),
    OpCode::new(0x8e, &STX, Absolute, 4),
    OpCode::new(0x8f, &KIL, Implied, 0),
    OpCode::new(0x90, &BCC, Branch, 2),
    OpCode::new(0x91, &STA, IndirectIndexedY, 6),
    OpCode::new(0x92, &KIL, Implied, 0),
    OpCode::new(0x93, &KIL, Implied, 0),
    OpCode::new(0x94, &STY, ZeroPageX, 4),
    OpCode::new(0x95, &STA, ZeroPageX, 4),
    OpCode::new(0x96, &STX, ZeroPageY, 4),
    OpCode::new(0x97, &KIL, Implied, 0),
    OpCode::new(0x98, &TYA, Implied, 2),
    OpCode::new(0x99, &STA, AbsoluteY, 5),
    OpCode::new(0x9a, &TXS, Implied, 2),
    OpCode::new(0x9b, &KIL, Implied, 0),
    OpCode::new(0x9c, &KIL, Implied, 0),
    OpCode::new(0x9d, &STA, AbsoluteX, 5),
    OpCode::new(0x9e, &KIL, Implied, 0),
    OpCode::new(0x9f, &KIL, Implied, 0),
    OpCode::new(0xa0, &LDY, Immediate, 2),
    OpCode::new(0xa1, &LDA, IndexedIndirectX, 6),
    OpCode::new(0xa2, &LDX, Immediate, 2),
    OpCode::new(0xa3, &KIL, Implied, 0),
    OpCode::new(0xa4, &LDY, ZeroPage, 3),
    OpCode::new(0xa5, &LDA, ZeroPage, 3),
    OpCode::new(0xa6, &LDX, ZeroPage, 3),
    OpCode::new(0xa7, &KIL, Implied, 0),
    OpCode::new(0xa8, &TAY, Implied, 2),
    OpCode::new(0xa9, &LDA, Immediate, 2),
    OpCode::new(0xaa, &TAX, Implied, 2),
    OpCode::new(0xab, &KIL, Implied, 0),
    OpCode::new(0xac, &LDY, Absolute, 4),
    OpCode::new(0xad, &LDA, Absolute, 4),
    OpCode::new(0xae, &LDX, Absolute, 4),
    OpCode::new(0xaf, &KIL, Implied, 0),
    OpCode::new(0xb0, &BCS, Branch, 2),
    OpCode::new(0xb1, &LDA, IndirectIndexedY, 5),
    OpCode::new(0xb2, &KIL, Implied, 0),
    OpCode::new(0xb3, &KIL, Implied, 0),
    OpCode::new(0xb4, &LDY, ZeroPageX, 4),
    OpCode::new(0xb5, &LDA, ZeroPageX, 4),
    OpCode::new(0xb6, &LDX, ZeroPageY, 4),
    OpCode::new(0xb7, &KIL, Implied, 0),
    OpCode::new(0xb8, &CLV, Implied, 2),
    OpCode::new(0xb9, &LDA, AbsoluteY, 4),
    OpCode::new(0xba, &TSX, Implied, 2),
    OpCode::new(0xbb, &KIL, Implied, 0),
    OpCode::new(0xbc, &LDY, AbsoluteX, 4),
    OpCode::new(0xbd, &LDA, AbsoluteX, 4),
    OpCode::new(0xbe, &LDX, AbsoluteY, 4),
    OpCode::new(0xbf, &KIL, Implied, 0),
    OpCode::new(0xc0, &CPY, Immediate, 2),
    OpCode::new(0xc1, &CMP, IndexedIndirectX, 6),
    OpCode::new(0xc2, &KIL, Implied, 0),
    OpCode::new(0xc3, &KIL, Implied, 0),
    OpCode::new(0xc4, &CPY, ZeroPage, 3),
    OpCode::new(0xc5, &CMP, ZeroPage, 3),
    OpCode::new(0xc6, &DEC, ZeroPage, 5),
    OpCode::new(0xc7, &KIL, Implied, 0),
    OpCode::new(0xc8, &INY, Implied, 2),
    OpCode::new(0xc9, &CMP, Immediate, 2),
    OpCode::new(0xca, &DEX, Implied, 2),
    OpCode::new(0xcb, &KIL, Implied, 0),
    OpCode::new(0xcc, &CPY, Absolute, 4),
    OpCode::new(0xcd, &CMP, Absolute, 4),
    OpCode::new(0xce, &DEC, Absolute, 6),
    OpCode::new(0xcf, &KIL, Implied, 0),
    OpCode::new(0xd0, &BNE, Branch, 2),
    OpCode::new(0xd1, &CMP, IndirectIndexedY, 5),
    OpCode::new(0xd2, &KIL, Implied, 0),
    OpCode::new(0xd3, &KIL, Implied, 0),
    OpCode::new(0xd4, &KIL, Implied, 0),
    OpCode::new(0xd5, &CMP, ZeroPageX, 4),
    OpCode::new(0xd6, &DEC, ZeroPageX, 6),
    OpCode::new(0xd7, &KIL, Implied, 0),
    OpCode::new(0xd8, &CLD, Implied, 2),
    OpCode::new(0xd9, &CMP, AbsoluteY, 4),
    OpCode::new(0xda, &KIL, Implied, 0),
    OpCode::new(0xdb, &KIL, Implied, 0),
    OpCode::new(0xdc, &KIL, Implied, 0),
    OpCode::new(0xdd, &KIL, Implied, 0),
    OpCode::new(0xde, &CMP, AbsoluteX, 4),
    OpCode::new(0xdf, &DEC, AbsoluteX, 7),
    OpCode::new(0xe0, &CPX, Immediate, 2),
    OpCode::new(0xe1, &SBC, IndexedIndirectX, 6),
    OpCode::new(0xe2, &KIL, Implied, 0),
    OpCode::new(0xe3, &KIL, Implied, 0),
    OpCode::new(0xe4, &CPX, ZeroPage, 3),
    OpCode::new(0xe5, &SBC, ZeroPage, 3),
    OpCode::new(0xe6, &INC, ZeroPage, 5),
    OpCode::new(0xe7, &KIL, Implied, 0),
    OpCode::new(0xe8, &INX, Implied, 2),
    OpCode::new(0xe9, &SBC, Immediate, 2),
    OpCode::new(0xea, &NOP, Implied, 2),
    OpCode::new(0xeb, &KIL, Implied, 0),
    OpCode::new(0xec, &CPX, Absolute, 4),
    OpCode::new(0xed, &SBC, Absolute, 4),
    OpCode::new(0xee, &INC, Absolute, 6),
    OpCode::new(0xef, &KIL, Implied, 0),
    OpCode::new(0xf0, &BEQ, Branch, 2),
    OpCode::new(0xf1, &SBC, IndirectIndexedY, 5),
    OpCode::new(0xf2, &KIL, Implied, 0),
    OpCode::new(0xf3, &KIL, Implied, 0),
    OpCode::new(0xf4, &KIL, Implied, 0),
    OpCode::new(0xf5, &SBC, ZeroPageX, 4),
    OpCode::new(0xf6, &INC, ZeroPageX, 6),
    OpCode::new(0xf7, &KIL, Implied, 0),
    OpCode::new(0xf8, &SED, Implied, 2),
    OpCode::new(0xf9, &SBC, AbsoluteY, 4),
    OpCode::new(0xfa, &KIL, Implied, 0),
    OpCode::new(0xfb, &KIL, Implied, 0),
    OpCode::new(0xfc, &KIL, Implied, 0),
    OpCode::new(0xfd, &SBC, AbsoluteX, 4),
    OpCode::new(0xfe, &INC, AbsoluteX, 7),
    OpCode::new(0xff, &KIL, Implied, 0),
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_find_opcode() {
        match find_opcode(&SEI, Implied) {
            Some(oc) => assert_eq!(oc.code, 0x78),
            None => assert!(false, "opcode not found"),
        }
    }
}
