#unstable_features = true
max_width = 140
use_field_init_shorthand = true
#where_single_line = true
#reorder_modules = false
# single_line_if_else_max_width = 100
#blank_lines_lower_bound = 2
#struct_variant_width = 80
#struct_lit_single_line = true